// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Terestre",
    platforms: [
        .iOS("17")
    ],
    products: [
        .iOSApplication(
            name: "Terestre",
            targets: ["AppModule"],
            bundleIdentifier: "org.jhhs.627115.ClimateChangeGroupApp",
            teamIdentifier: "U34DP379RQ",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .earth),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-algorithms.git", "1.2.1"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Algorithms", package: "swift-algorithms")
            ],
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)